baseURL = '/'
relativeURLs = true
canonifyURLs = false
languageCode = 'en-us'
title = 'Montana Guard Cyber'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
omit_header_text = true
[[params.ananke_socials]]
  name = "GitHub"
  url = "https://github.com/mtguardcyber/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 3